=== RozebMomin/KodiAddons/plugin.video.tvondesizonexl/xoze.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="https://code.google.com/p/apple-tv2-xbmc/xoze/"
	targetNamespace="https://code.google.com/p/apple-tv2-xbmc/xoze/"
	elementFormDefault="qualified">


	<xs:annotation>
		<xs:documentation>XOZE is brand new well-documented MVC based XBMC
			add-on framework.
		</xs:documentation>
	</xs:annotation>
	<xs:complexType name="action-type">
		<xs:sequence>
			<xs:element name="move" type="tns:move-type" minOccurs="1"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="move-type">
		<xs:attribute name="module" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="function" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="view-id" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="redirect-id" type="xs:string" use="optional"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="view-type">
		<xs:sequence>
			<xs:element name="event" type="tns:event-type" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="module" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="function" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="event-type">
		<xs:attribute name="intent" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="control-id" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="module" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="function" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="action-id" type="xs:string" use="optional"></xs:attribute>
	</xs:complexType>

	<xs:element name="actions" type="tns:actions-type"></xs:element>

	<xs:complexType name="actions-type" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="action" type="tns:action-type">
			</xs:element>
			<xs:element name="service" type="tns:service-type"></xs:element>
			<xs:element name="view" type="tns:view-type"></xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="service-type">
		<xs:attribute name="path" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="action-id" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="module" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="function" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>
</xs:schema>

=== RozebMomin/KodiAddons/plugin.video.tvondesizonexl/dtf_actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://code.google.com/p/apple-tv2-xbmc/xoze/ xoze.xsd"
	xmlns="https://code.google.com/p/apple-tv2-xbmc/xoze/">
	<action id="dtf-checkCache">
		<move module="tvshows.dtf_actions" function="coming_soon" view-id="dtf-soonView" />
	</action>
	<!-- 
	<action id="dtf-checkCache">
		<move module="tvshows.dtf_actions" function="check_cache" view-id="dtf-refreshView" />
		<move module="tvshows.dtf_actions" function="refresh_cache" />
		<move module="tvshows.dtf_actions" function="load_channels" view-id="dtf-channelsView" />
	</action> -->
	
	<action id="dtf-displayShowsList">
		<move module="tvshows.dtf_actions" function="load_tv_shows" view-id="dtf-tvShowsView" />
	</action>
	
	
	<view id="dtf-channelsView" function="show_channels_view" module="tvshows.dtf_views">
		<event function="handle_channel_selected" module="tvshows.dtf_views" action-id="dtf-displayShowsList" control-id="102" intent="ACTION_MOUSE_LEFT_CLICK" />
		<event function="handle_channel_selected" module="tvshows.dtf_views" action-id="dtf-displayShowsList" control-id="102" intent="ACTION_SELECT_ITEM" />
		<event function="handle_channel_selected" module="tvshows.dtf_views" action-id="dtf-displayShowsList" control-id="102" intent="ACTION_ENTER" />
		<event function="handle_channel_selected" module="tvshows.dtf_views" action-id="dtf-displayShowsList" control-id="102" intent="ACTION_TOUCH_TAP" />
		<event action-id="end" control-id="" intent="ACTION_PREVIOUS_MENU" />
		<event action-id="end" control-id="" intent="ACTION_NAV_BACK" />
		<event action-id="end" control-id="" intent="ACTION_PARENT_DIR" />
		<event action-id="end" control-id="" intent="ACTION_TOUCH_TAP_TEN" />
	</view>
	
	<view id="dtf-tvShowsView" function="show_tv_shows_view" module="tvshows.dtf_views">
		<event action-id="determineSource" control-id="" intent="ACTION_PREVIOUS_MENU" />
		<event action-id="determineSource" control-id="" intent="ACTION_NAV_BACK" />
		<event action-id="determineSource" control-id="" intent="ACTION_PARENT_DIR" />
		<event action-id="determineSource" control-id="" intent="ACTION_TOUCH_TAP_TEN" />
		<event action-id="dtf-displayShowEpisodesList" function="handle_tv_show_selected" module="tvshows.dtf_views" control-id="305" intent="ACTION_MOUSE_LEFT_CLICK" />
		<event action-id="dtf-displayShowEpisodesList" function="handle_tv_show_selected" module="tvshows.dtf_views" control-id="305" intent="ACTION_SELECT_ITEM" />
		<event action-id="dtf-displayShowEpisodesList" function="handle_tv_show_selected" module="tvshows.dtf_views" control-id="305" intent="ACTION_ENTER" />
		<event action-id="dtf-displayShowEpisodesList" function="handle_tv_show_selected" module="tvshows.dtf_views" control-id="305" intent="ACTION_TOUCH_TAP" />
	</view>
	
	<view id="dtf-refreshView" function="show_refresh_view" module="tvshows.dtf_views">
		<event action-id="end" control-id="" intent="ACTION_NAV_BACK" />
		<event action-id="end" control-id="" intent="ACTION_PARENT_DIR" />
		<event action-id="end" control-id="" intent="ACTION_TOUCH_TAP_TEN" />
		<event action-id="end" control-id="" intent="ACTION_PREVIOUS_MENU" />
	</view>
	
	<view id="dtf-soonView" function="show_soon_view" module="tvshows.dtf_views">
		<event action-id="end" control-id="" intent="ACTION_NAV_BACK" />
		<event action-id="end" control-id="" intent="ACTION_PARENT_DIR" />
		<event action-id="end" control-id="" intent="ACTION_TOUCH_TAP_TEN" />
		<event action-id="end" control-id="" intent="ACTION_PREVIOUS_MENU" />
	</view>
</actions>

=== RozebMomin/KodiAddons/plugin.video.tvondesizonexl/actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://code.google.com/p/apple-tv2-xbmc/xoze/ xoze.xsd"
	xmlns="https://code.google.com/p/apple-tv2-xbmc/xoze/">
	
	<service path="resolveStream" action-id="resolveStream" module="tvshows.actions" function="set_stream_in_response"/>
	
	<action id="resolveStream">
		<move  module="tvshows.actions" function="resolve_stream"/>
	</action>
	
	<action id="start">
		<move module="tvshows.actions" function="start_addon" view-id="startView" />
	</action>
	
	<action id="wishBoard">
		<move module="tvshows.actions" function="check_wish" />
		<move module="tvshows.actions" function="display_wish" view-id="wishView"/>
	</action>
	
	<action id="displaySourceList">
		<move module="tvshows.actions" function="load_source_list" view-id="tvSourceView"  />
	</action>
	
	<action id="determineSource">
		<move module="tvshows.actions" function="determine_source" />
	</action>
	
	<action id="viewSourceOrEnd">
		<move module="tvshows.actions" function="end_menu" />
	</action>

	<action id="end">
		<move module="tvshows.actions" function="end_addon" />
	</action>
	
	<view id="tvSourceView" function="show_tv_source_view" module="tvshows.views">
		<event function="handle_tv_source_selected" module="tvshows.views" action-id="determineSource" control-id="1202" intent="ACTION_MOUSE_LEFT_CLICK" />
		<event function="handle_tv_source_selected" module="tvshows.views" action-id="determineSource" control-id="1202" intent="ACTION_SELECT_ITEM" />
		<event function="handle_tv_source_selected" module="tvshows.views" action-id="determineSource" control-id="1202" intent="ACTION_ENTER" />
		<event function="handle_tv_source_selected" module="tvshows.views" action-id="determineSource" control-id="1202" intent="ACTION_TOUCH_TAP" />
		
		<event action-id="end" control-id="10" intent="ACTION_MOUSE_LEFT_CLICK" />
		<event action-id="end" control-id="10" intent="ACTION_SELECT_ITEM" />
		<event action-id="end" control-id="10" intent="ACTION_ENTER" />
		<event action-id="end" control-id="10" intent="ACTION_TOUCH_TAP" />
		
		<event action-id="end" control-id="" intent="ACTION_PREVIOUS_MENU" />
		<event action-id="end" control-id="" intent="ACTION_NAV_BACK" />
		<event action-id="end" control-id="" intent="ACTION_PARENT_DIR" />
		<event action-id="end" control-id="" intent="ACTION_TOUCH_TAP_TEN" />
	</view>

	<view id="startView" function="show_start_view" module="tvshows.views">
		<event action-id="end" control-id="" intent="ACTION_PREVIOUS_MENU" />
		<event action-id="end" control-id="" intent="ACTION_NAV_BACK" />
		<event action-id="end" control-id="" intent="ACTION_PARENT_DIR" />
		<event action-id="end" control-id="" intent="ACTION_TOUCH_TAP_TEN" />
		<event action-id="wishBoard" function="handle_init" module="tvshows.views"  control-id="" intent="INIT" />
	</view>
	
	<view id="wishView" function="show_wish_view" module="tvshows.views">
		<event action-id="end" control-id="" intent="ACTION_PREVIOUS_MENU" />
		<event action-id="end" control-id="" intent="ACTION_NAV_BACK" />
		<event action-id="end" control-id="" intent="ACTION_PARENT_DIR" />
		<event action-id="end" control-id="" intent="ACTION_TOUCH_TAP_TEN" />
		<event function="handle_wish_closed" module="tvshows.views" action-id="displaySourceList" control-id="701" intent="ACTION_MOUSE_LEFT_CLICK" />
		<event function="handle_wish_closed" module="tvshows.views" action-id="displaySourceList" control-id="701" intent="ACTION_SELECT_ITEM" />
		<event function="handle_wish_closed" module="tvshows.views" action-id="displaySourceList" control-id="701" intent="ACTION_ENTER" />
		<event function="handle_wish_closed" module="tvshows.views" action-id="displaySourceList" control-id="701" intent="ACTION_TOUCH_TAP" />
	</view>

</actions>
